In [1]:
import numpy as np
from sklearn.datasets import make_classification, load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import torch

In [2]:
# X, y = make_classification(n_samples=99999, n_informative= 4,n_classes=3)
X,y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

y_train = y_train
y_test = y_test

enc = OneHotEncoder()
y_train_1h = enc.fit_transform(y_train.reshape(-1,1))
y_test_1h = enc.transform(y_test.reshape(-1,1))

In [3]:
X_train

array([[5.9, 3. , 5.1, 1.8],
       [5. , 3.2, 1.2, 0.2],
       [6. , 2.2, 4. , 1. ],
       [5.8, 4. , 1.2, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [7.7, 3. , 6.1, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.8, 3. , 5.5, 2.1],
       [4.8, 3.4, 1.6, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [4.8, 3.4, 1.9, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [4.9, 3.6, 1.4, 0.1],
       [6.7, 3.1, 4.7, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.5, 3.9, 1.1],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [5.6, 2.7, 4.2, 1.3],
       [5. , 2. , 3.5, 1. ],
       [5.7, 2

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clf = LogisticRegression()

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.98

In [5]:
from simple_model import ClassifierModel, TabularDataset
from torch.utils.data import DataLoader

In [6]:
model = ClassifierModel(input_dim=X_train.shape[1], hidden_dim=16, output_dim=3)
train_dataset = TabularDataset(X_train, y_train)
test_dataset = TabularDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

for batch in train_loader:
    print(batch)

[tensor([[7.9000, 3.8000, 6.4000, 2.0000],
        [6.8000, 2.8000, 4.8000, 1.4000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [5.9000, 3.0000, 5.1000, 1.8000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [5.9000, 3.0000, 4.2000, 1.5000],
        [5.4000, 3.4000, 1.7000, 0.2000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [6.5000, 3.0000, 5.8000, 2.2000],
        [6.0000, 2.2000, 5.0000, 1.5000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [6.0000, 2.7000, 5.1000, 1.6000],
        [5.7000, 2.8000, 4.5000, 1.3000],
        [6.7000, 2.5000, 5.8000, 1.8000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [6.3000, 2.9000, 5.6000, 1.8000],
        [5.5000, 2.4000, 3.8000, 

In [7]:
print(model)

ClassifierModel(
  (input): Linear(in_features=4, out_features=16, bias=True)
  (hidden): Linear(in_features=16, out_features=3, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.25, inplace=False)
)


In [8]:
# model.fit(train_dataset)

In [9]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total:.2f}%')

Accuracy: 28.00%


In [10]:
y_train

array([2, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 0, 2, 0, 1, 1, 2,
       1, 1, 2, 1, 0, 1, 2, 1, 2, 2, 1, 1, 1, 2, 0, 0, 0, 1, 1, 2, 0, 2,
       2, 0, 1, 1, 1, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 2,
       0, 1, 2, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0,
       0, 0, 0, 2, 2, 2, 1, 0, 0, 2, 1, 0])

In [11]:
from simple_model import DyadOneHotPairDataset


In [12]:
dyadic_dataset_train = DyadOneHotPairDataset(X_train, y_train)
dyadic_dataset_test = DyadOneHotPairDataset(X_test, y_test)

train_loader = DataLoader(dyadic_dataset_train)
test_loader = DataLoader(dyadic_dataset_train)

In [13]:
from simple_model import DyadRankingModel
dyad_model = DyadRankingModel(input_dim=7,hidden_dim=16, output_dim=1)
dyad_model.fit(train_loader)

In [15]:
with torch.no_grad():
    for inputs in test_loader:
        outputs = dyad_model(inputs)
        print(outputs)


tensor([[[ -7.0091],
         [-19.9508]]])
tensor([[[ -7.0091],
         [-10.2980]]])
tensor([[[ -8.9415],
         [-14.5235]]])
tensor([[[ -8.9415],
         [-21.3455]]])
tensor([[[-2.9220],
         [-9.3085]]])
tensor([[[-2.9220],
         [-8.6841]]])
tensor([[[-12.0634],
         [-17.6453]]])
tensor([[[-12.0634],
         [-24.4674]]])
tensor([[[-10.4622],
         [-23.5820]]])
tensor([[[-10.4622],
         [-13.7559]]])
tensor([[[ -6.6767],
         [-19.7001]]])
tensor([[[-6.6767],
         [-9.9705]]])
tensor([[[ -9.3945],
         [-22.7958]]])
tensor([[[ -9.3945],
         [-12.6883]]])
tensor([[[ -7.5967],
         [-21.0735]]])
tensor([[[ -7.5967],
         [-10.8905]]])
tensor([[[ -9.3343],
         [-23.1726]]])
tensor([[[ -9.3343],
         [-12.8369]]])
tensor([[[ -8.7353],
         [-21.9678]]])
tensor([[[ -8.7353],
         [-12.0291]]])
tensor([[[ -6.7186],
         [-19.7834]]])
tensor([[[ -6.7186],
         [-10.0124]]])
tensor([[[ -2.9935],
         [-10.060