In [1]:
import numpy as np
from sklearn.datasets import make_classification, load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import torch

In [2]:
# X, y = make_classification(n_samples=99999, n_informative = 2, n_classes=3, n_features=4)
X,y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

y_train = y_train
y_test = y_test

enc = OneHotEncoder()
y_train_1h = enc.fit_transform(y_train.reshape(-1,1))
y_test_1h = enc.transform(y_test.reshape(-1,1))

In [3]:
X_train

array([[5. , 3.4, 1.5, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.9, 3.6, 1.4, 0.1],
       [5.7, 2.9, 4.2, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [6.4, 2.8, 5.6, 2.2],
       [6.1, 3. , 4.9, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [4.8, 3.1, 1.6, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [7.6, 3. , 6.6, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [6.4, 3.2, 5.3, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.4, 3.9, 1.7, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.6, 3. , 4.4, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 3. , 4.2, 1.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.3, 3

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clf = LogisticRegression()

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.96

In [5]:
from simple_model import ClassifierModel, TabularDataset
from torch.utils.data import DataLoader

In [6]:
model = ClassifierModel(input_dim=X_train.shape[1], hidden_dim=16, output_dim=3)
train_dataset = TabularDataset(X_train, y_train)
test_dataset = TabularDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

for batch in train_loader:
    print(batch)

[tensor([[6.4000, 2.8000, 5.6000, 2.2000],
        [6.9000, 3.1000, 4.9000, 1.5000],
        [6.0000, 2.2000, 5.0000, 1.5000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [4.9000, 3.6000, 1.4000, 0.1000],
        [6.0000, 2.9000, 4.5000, 1.5000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.3000, 3.7000, 1.5000, 0.2000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [7.7000, 3.0000, 6.1000, 2.3000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [6.2000, 2.2000, 4.5000, 1.5000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [4.9000, 3.1000, 1.5000, 0.2000],
        [6.4000, 2.9000, 4.3000, 

In [7]:
print(model)

ClassifierModel(
  (input): Linear(in_features=4, out_features=16, bias=True)
  (hidden): Linear(in_features=16, out_features=3, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.25, inplace=False)
)


In [8]:
model.fit(train_dataset)

tensor(0)
tensor(2)
tensor(2)
tensor(0)
tensor(0)
tensor(1)
tensor(0)
tensor(0)
tensor(2)
tensor(2)
tensor(2)
tensor(0)
tensor(1)
tensor(0)
tensor(0)
tensor(0)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(0)
tensor(1)
tensor(0)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(0)
tensor(0)
tensor(1)
tensor(2)
tensor(0)
tensor(1)
tensor(0)
tensor(1)
tensor(2)
tensor(1)
tensor(1)
tensor(0)
tensor(2)
tensor(2)
tensor(1)
tensor(1)
tensor(2)
tensor(1)
tensor(2)
tensor(1)
tensor(2)
tensor(1)
tensor(2)
tensor(1)
tensor(0)
tensor(2)
tensor(2)
tensor(0)
tensor(2)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(1)
tensor(1)
tensor(1)
tensor(2)
tensor(2)
tensor(1)
tensor(0)
tensor(2)
tensor(2)
tensor(1)
tensor(2)
tensor(2)
tensor(0)
tensor(1)
tensor(2)
tensor(0)
tensor(1)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(1)
tensor(1)
tensor(2)
tensor(0)
tensor(2)
tensor(1)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(1)


In [9]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total:.2f}%')

Accuracy: 98.00%


In [10]:
y_train

array([0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 2, 2, 2, 2, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1,
       0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       1, 1, 1, 2, 2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 1])

In [11]:
from simple_model import DyadOneHotPairDataset


In [12]:
dyadic_dataset_train = DyadOneHotPairDataset(X_train, y_train)
dyadic_dataset_test = DyadOneHotPairDataset(X_test, y_test)

train_loader = DataLoader(dyadic_dataset_train)
test_loader = DataLoader(dyadic_dataset_train)

In [13]:
from simple_model import DyadRankingModel
num_classes = y_train.max() + 1 
dyad_dim = X_train.shape[1] + num_classes

dyad_model = DyadRankingModel(input_dim=dyad_dim,hidden_dim=16, num_classes=num_classes)
dyad_model.fit(train_loader)

In [14]:
with torch.no_grad():
    for inputs in test_loader:
        outputs = dyad_model(inputs)
        print(outputs)


tensor([[[4.8709],
         [2.0488]]])
tensor([[[4.8709],
         [0.7614]]])
tensor([[[-2.9984],
         [-6.8815]]])
tensor([[[-2.9984],
         [-4.6720]]])
tensor([[[-2.5805],
         [-6.7457]]])
tensor([[[-2.5805],
         [-4.0224]]])
tensor([[[4.9715],
         [2.0756]]])
tensor([[[4.9715],
         [0.8441]]])
tensor([[[5.1127],
         [2.2216]]])
tensor([[[5.1127],
         [1.0091]]])
tensor([[[-0.7643],
         [-4.2879]]])
tensor([[[-0.7643],
         [-1.6835]]])
tensor([[[4.3195],
         [1.9579]]])
tensor([[[4.3195],
         [0.4528]]])
tensor([[[4.9963],
         [2.1269]]])
tensor([[[4.9963],
         [0.8744]]])
tensor([[[-3.1171],
         [-6.9465]]])
tensor([[[-3.1171],
         [-4.8629]]])
tensor([[[-2.1409],
         [-5.9381]]])
tensor([[[-2.1409],
         [-2.4676]]])
tensor([[[-2.2887],
         [-6.2496]]])
tensor([[[-2.2887],
         [-2.9961]]])
tensor([[[4.5192],
         [1.8947]]])
tensor([[[4.5192],
         [0.4998]]])
tensor([[[-1.059

In [35]:
X = torch.tensor(X_test, dtype=torch.float32)
eye = torch.eye(num_classes)

In [56]:
eyes = eye.repeat((X.shape[0],1))
Xs = X.repeat_interleave(num_classes,dim=0)
result = torch.cat([Xs,eyes],dim=1)

In [58]:
result

tensor([[5.0000, 3.4000, 1.5000,  ..., 1.0000, 0.0000, 0.0000],
        [5.0000, 3.4000, 1.5000,  ..., 0.0000, 1.0000, 0.0000],
        [5.0000, 3.4000, 1.5000,  ..., 0.0000, 0.0000, 1.0000],
        ...,
        [5.5000, 2.3000, 4.0000,  ..., 1.0000, 0.0000, 0.0000],
        [5.5000, 2.3000, 4.0000,  ..., 0.0000, 1.0000, 0.0000],
        [5.5000, 2.3000, 4.0000,  ..., 0.0000, 0.0000, 1.0000]])

In [68]:
preds = dyad_model(result)
preds

tensor([[ 4.8709],
        [ 2.0488],
        [ 0.7614],
        [-6.8815],
        [-4.6720],
        [-2.9984],
        [-6.7457],
        [-4.0224],
        [-2.5805],
        [ 4.9715],
        [ 2.0756],
        [ 0.8441],
        [ 5.1127],
        [ 2.2216],
        [ 1.0091],
        [-4.2879],
        [-0.7643],
        [-1.6835],
        [ 4.3195],
        [ 1.9579],
        [ 0.4528],
        [ 4.9963],
        [ 2.1269],
        [ 0.8744],
        [-6.9465],
        [-4.8629],
        [-3.1171],
        [-5.9381],
        [-2.4676],
        [-2.1409],
        [-6.2496],
        [-2.9961],
        [-2.2887],
        [ 4.5192],
        [ 1.8947],
        [ 0.4998],
        [-4.6679],
        [-1.0590],
        [-1.7646],
        [ 4.8449],
        [ 2.0627],
        [ 0.7263],
        [ 4.6278],
        [ 1.9592],
        [ 0.5671],
        [ 4.8069],
        [ 2.0084],
        [ 0.7257],
        [-7.0389],
        [-4.9763],
        [-3.1242],
        [-6.4007],
        [-3.

In [67]:
preds.view(-1,3)

tensor([[ 4.8709,  2.0488,  0.7614],
        [-6.8815, -4.6720, -2.9984],
        [-6.7457, -4.0224, -2.5805],
        [ 4.9715,  2.0756,  0.8441],
        [ 5.1127,  2.2216,  1.0091],
        [-4.2879, -0.7643, -1.6835],
        [ 4.3195,  1.9579,  0.4528],
        [ 4.9963,  2.1269,  0.8744],
        [-6.9465, -4.8629, -3.1171],
        [-5.9381, -2.4676, -2.1409],
        [-6.2496, -2.9961, -2.2887],
        [ 4.5192,  1.8947,  0.4998],
        [-4.6679, -1.0590, -1.7646],
        [ 4.8449,  2.0627,  0.7263],
        [ 4.6278,  1.9592,  0.5671],
        [ 4.8069,  2.0084,  0.7257],
        [-7.0389, -4.9763, -3.1242],
        [-6.4007, -3.2512, -2.3508],
        [-6.1011, -2.6738, -2.1977],
        [-6.5532, -3.6757, -2.5040],
        [-6.6119, -4.0173, -2.6831],
        [ 4.7238,  1.8937,  0.6368],
        [-3.7658, -0.4515, -1.5963],
        [ 4.9497,  2.0826,  0.8393],
        [-3.3667, -0.2459, -1.4963],
        [-3.4124, -0.2918, -1.5495],
        [-4.3508, -0.8181, -1.7254],
 

In [71]:
class_preds = preds.view(-1,3).argmax(axis=1)
class_preds

tensor([0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 2, 2, 2, 2, 0, 1, 0,
        1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 0, 2, 2, 1,
        1, 2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1,
        0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2, 2,
        2, 2, 2, 1])

In [73]:
y_pred = class_preds.numpy()

In [74]:
y_pred

array([0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 2, 2, 2, 2, 0,
       1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1,
       0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       1, 1, 1, 2, 2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0,
       1, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 1])

In [75]:
y_test

array([0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 2, 2, 2, 2, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1,
       0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       1, 1, 1, 2, 2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2, 1])

In [76]:
accuracy_score(y_pred,y_test)

0.98